### ISSUE TITLE
Error thrown when player joins while already on horse

### ISSUE THREAD

**Issue by IR0NSIGHT** [Edgeburn/Horse-Highway#9] opened 2023-05-31 11:57 UTC
tested on my small MP server, log out while on horse, log in => still on horse.
no speedometer pops up and console shows error.
get off horse and back on fixes issue
tested in 1.19.4

[13:54:54] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to HorseHighway vbeta-5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:681) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.network.protocol.game.PacketPlayInVehicleMove.a(SourceFile:41) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.network.protocol.game.PacketPlayInVehicleMove.a(SourceFile:7) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.util.thread.IAsyncTaskHandler.br(SourceFile:115) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1109) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3753-Spigot-7d7b241-b346a5f]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.edgeburnmedia.horsehighway.HorseManager.updateSpeed(org.bukkit.Material)" because the return value of "java.util.HashMap.get(Object)" is null
at com.edgeburnmedia.horsehighway.HorseHighwayListeners.onPlayerMove(HorseHighwayListeners.java:35) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
... 20 more

**Comment by Edgeburn** [comment] 2023-06-03 05:12
While I was unable to reproduce this issue in my testing environment, it should be fixed by bd4bb9b. Please try the attached build and see if it fixes the problem
[HorseHighway-beta-6-SNAPSHOT.zip](https://github.com/Edgeburn/Horse-Highway/files/11641777/HorseHighway-beta-6-SNAPSHOT.zip)

**Closed as completed** 2023-06-03 06:31 UTC
